### ISSUE TITLE
CSS formatting

### ISSUE THREAD

**Issue by willthemoor** [vladocar/1-line-CSS-Framework#2]
https://github.com/vladocar/1-line-CSS-Framework/blob/703b1c1d873fb06f4f805f2f5621dd269b4b5d74/grid.css#L1

Please sort the property order for increased developer legibility. Also, it's important to consider performance: the last semi-colon is not required. But this one is --> ;)
```css
.dp50{float:left;width:50%}
```

**Comment by vladocar** [comment]
Agreed ;)
